name: fun_android
description: Fun or Flutter for Android

version: 0.1.2+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^0.1.2

  # State
  provider: ^3.0.0+1

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.13
  flutter_webview_plugin: ^0.3.7
  device_info: ^0.4.0+1
  package_info: ^0.4.0+3
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^2.1.13
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.2+2
  # 本地json对象存储
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.10.4

  # 判断list是否相等
  collection: ^1.14.11
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.1.7
  pull_to_refresh: ^1.5.4
  flutter_swiper: ^1.1.6
  cached_network_image: ^1.1.1
  # 类iOS侧滑菜单
  flutter_slidable: 0.5.3
  # 谁用谁闪亮
  shimmer: ^1.0.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.2.0
  flare_flutter: 1.5.5

  # third_app
  share: 0.6.2+1 #分享
  url_launcher: ^5.1.2 #启动第三方app

  # 评分
  launch_review: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

#  build_runner: ^1.6.2
#  json_serializable: ^3.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/images/
    - assets/animations/
    - CHANGELOG.md

